# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iterate_layout <- function(xyr, weights, xmin, xmax, ymin, ymax, maxiter, wrap) {
    .Call(`_packcircles_iterate_layout`, xyr, weights, xmin, xmax, ymin, ymax, maxiter, wrap)
}

doCirclePack <- function(internalList, externalDF) {
    .Call(`_packcircles_doCirclePack`, internalList, externalDF)
}

do_progressive_layout <- function(radii) {
    .Call(`_packcircles_do_progressive_layout`, radii)
}

select_non_overlapping <- function(xyr, tolerance, ordering) {
    .Call(`_packcircles_select_non_overlapping`, xyr, tolerance, ordering)
}

