# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iterate_layout <- function(xyr, weights, xmin, xmax, ymin, ymax, maxiter, wrap) {
    .Call('packcircles_iterate_layout', PACKAGE = 'packcircles', xyr, weights, xmin, xmax, ymin, ymax, maxiter, wrap)
}

doCirclePack <- function(internalList, externalDF) {
    .Call('packcircles_doCirclePack', PACKAGE = 'packcircles', internalList, externalDF)
}

do_progressive_layout <- function(radii) {
    .Call('packcircles_do_progressive_layout', PACKAGE = 'packcircles', radii)
}

