# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iterate_layout <- function(xyr, xbound, ybound, maxiter) {
    .Call('packcircles_iterate_layout', PACKAGE = 'packcircles', xyr, xbound, ybound, maxiter)
}

